### ISSUE TITLE
[Epic] Integration testing Issues

### ISSUE THREAD

**Issue by zognin** [Giving-Coupons/giving-coupons#184]
- [x] #193
- [x] #196
- [x] #195
- [x] #194
- [x] #197
- [x] Edit campaign, image is not carried over
- [x] nginx does cannot point to subpaths e.g. it cannot go directly to /admin/campaigns/1
- [x] Charity form image and logo fields are accidentally the same
- [x] #198
- [x] #199
- [x] Edit campaign with new charities makes form invalid
- [x] #200
- [x] restore typography variant h5
- [x] #201
- [x] #202
- [x] #203
- [x] favicon icons not found
- [x] #204
- [x] #205
